[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32H723ZGTx"

rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",

  # Code-size optimizations.
  #   trap unreachable can save a lot of space, but requires nightly compiler.
  #   uncomment the next line if you wish to enable it
  # "-Z", "trap-unreachable=no",
  #"-C", "inline-threshold=5",
  #"-C", "no-vectorize-loops",
]

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[env]
DEFMT_LOG = "debug"

# thumbv7em-none-eabihf is not coming with core and alloc, compile myself
[unstable]
mtime-on-use = true
# either run `rustup target add --toolchain nightly thumbv7em-none-eabihf`
# or uncomment the next line to build core yourself, self-buildings allows LTO
# to optimise better
# build-std = [ "core"]
